- name: start Nestjs container
  hosts: all
  remote_user: barneo-tech
  become: true
  vars:
    - user: barneo-tech
    - DOCKER_HUB_BARNEO_NAME: "{{ lookup('env','DOCKER_HUB_BARNEO_NAME') }}"
    - DOCKER_HUB_BARNEO_PASS: "{{ lookup('env','DOCKER_HUB_BARNEO_PASS') }}"


  tasks:
#    - name: Install Docker
#      apt:
#       update_cache: yes
#       name: docker.io
#
#    - name: Install Docker-Compose
#      apt:
#       name: docker-compose
#
#    - name: Install Python Module
#      apt:
#       name: python3-pip
#
#    - name: Install Python Docker-Compose
#      pip:
#       name: docker-compose

    - name: Log into DockerHub
      docker_login:
        username: "{{ DOCKER_HUB_BARNEO_NAME }}"
        password: "{{ DOCKER_HUB_BARNEO_PASS }}"


#    - name: Create NestJS container
#      docker_container:
#        name: nestjs
#        image: barneotech/email-service:main
#        pull: yes
#        recreate: yes
#        restart: yes
#        ports:
#          - "8081:3000"
#


    - name: Creates directory
      file:
        path: "/home/barneo-tech/projects/project_01_email_service/dev/backend"
        state: directory

    - name: Copy file
      copy:
        src: "/home/runner/work/project_01_email_service_backend/project_01_email_service_backend/docker/docker-compose-01-backend.yml"
        dest: "/home/barneo-tech/projects/project_01_email_service/dev/backend/docker-compose.yml"


#    - name: Tear down existing services
#      docker_compose:
#        project_src: "/home/barneo-tech/projects/project_01_email_service/dev/backend"
#        state: absent

    - name: Stop all services
        docker_compose:
          project_src: "/home/barneo-tech/projects/project_01_email_service/dev/backend"
          build: no
          stopped: yes
        register: output


    - name: Prune unused images
      docker_prune:
        containers: yes
        images: yes
#       networks: yes
#       volumes: yes
        builder_cache: yes

    - name: Create and start services
      docker_compose:
        project_src: "/home/barneo-tech/projects/project_01_email_service/dev/backend"
      register: output

    - debug:
        var: output

    - name: Run `docker-compose up` again
      docker_compose:
        project_src: "/home/barneo-tech/projects/project_01_email_service/dev/backend"
        build: no
      register: output

    - debug:
        var: output




