# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image


on:
  push:
    branches: [ main ]

#trigger action by push to branch: main
#  push:
#    paths:
#     - 'app/**'

#    branches: [ main ]
#trigger action by publish new releases
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_BARNEO_NAME: '${{ secrets.DOCKER_HUB_BARNEO_NAME }}'
      DOCKER_HUB_BARNEO_PASS: '${{ secrets.DOCKER_HUB_BARNEO_PASS }}'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_BARNEO_NAME }}
          password: ${{ secrets.DOCKER_HUB_BARNEO_PASS }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: barneotech/email-service

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./app
          file: ./docker/Dockerfile
          no-cache: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: playbook.yml
          # Optional, directory where playbooks live
          directory: ./ansible/
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            all:
              hosts:
                barneo-tech:
                   ansible_host: ${{secrets.IP_SELECTEL_SERVER}}
 #                 ansible_sudo_pass: LyAMHFM4TjSwwCGgnnCc6QqJ

          # Optional, SSH known hosts file content
          # known_hosts: .known_hosts
          # Optional, encrypted vault password
          # vault_password: ${{secrets.VAULT_PASSWORD}}
          # Optional, galaxy requirements filepath
          # requirements: galaxy-requirements.yml
          # Optional, additional flags to pass to ansible-playbook
#          options: |
#            --inventory ~/
#            --limit group1
#            --extra-vars hello=there
#            --verbose


